### ISSUE TITLE
Build `error: 0-bit reloc in dll' using mingw 10.2.0

### ISSUE THREAD

**Issue by HuangShumin** [rmyorston/busybox-w32#200]
Has anyone encounter the same error?

```
  WINDRES win32/resources/resources.o
  LD      win32/resources/built-in.o
  LINK    busybox_unstripped.exe
Trying libraries: ws2_32
Failed: -Wl,--start-group  -lws2_32  -Wl,--end-group
Output of:
x86_64-w64-mingw32-gcc -Wall -Wshadow -Wwrite-strings -Wundef -Wstrict-prototypes -Wunused -Wunused-parameter -Wunused-function -Wunused-value -Wmissing-prototypes -Wmissing-declarations -Wno-format-security -Wdeclaration-after-statement -Wold-style-definition -finline-limit=0 -fno-builtin-strlen -fomit-frame-pointer -ffunction-sections -fdata-sections -fno-guess-branch-probability -funsigned-char -static-libgcc -falign-functions=1 -falign-jumps=1 -falign-labels=1 -falign-loops=1 -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-builtin-printf -g -Os -funwind-tables -fasynchronous-unwind-tables -Iwin32 -DHAVE_STRING_H=1 -DHAVE_CONFIG_H=0 -fno-builtin-stpcpy -fno-ident -fno-builtin-strndup -o busybox_unstripped.exe -Wl,--sort-common -Wl,--sort-section,alignment -Wl,--gc-sections -Wl,--start-group applets/built-in.o win32/resources/built-in.o archival/lib.a archival/libarchive/lib.a console-tools/lib.a coreutils/lib.a coreutils/libcoreutils/lib.a debianutils/lib.a klibc-utils/lib.a e2fsprogs/lib.a editors/lib.a findutils/lib.a init/lib.a libbb/lib.a libpwdgrp/lib.a loginutils/lib.a mailutils/lib.a miscutils/lib.a modutils/lib.a networking/lib.a networking/libiproute/lib.a networking/udhcp/lib.a printutils/lib.a procps/lib.a runit/lib.a selinux/lib.a shell/lib.a sysklogd/lib.a util-linux/lib.a util-linux/volume_id/lib.a win32/lib.a archival/built-in.o archival/libarchive/built-in.o console-tools/built-in.o coreutils/built-in.o coreutils/libcoreutils/built-in.o debianutils/built-in.o klibc-utils/built-in.o e2fsprogs/built-in.o editors/built-in.o findutils/built-in.o init/built-in.o libbb/built-in.o libpwdgrp/built-in.o loginutils/built-in.o mailutils/built-in.o miscutils/built-in.o modutils/built-in.o networking/built-in.o networking/libiproute/built-in.o networking/udhcp/built-in.o printutils/built-in.o procps/built-in.o runit/built-in.o selinux/built-in.o shell/built-in.o sysklogd/built-in.o util-linux/built-in.o util-linux/volume_id/built-in.o win32/built-in.o -Wl,--end-group -Wl,--start-group -lws2_32 -Wl,--end-group
==========
/mingw64/x86_64-w64-mingw32/bin/ld: error: 0-bit reloc in dll
```

**Comment by rmyorston** [comment]
I've just tried building on Fedora 33 (due for release next month) which has mingw64-gcc-10.2.1-2.fc33.x86_64 and mingw64-headers-7.0.0-2.fc33.noarch. The build failed with:
```
Trying libraries: ws2_32
Failed: -Wl,--start-group  -lws2_32  -Wl,--end-group
Output of:
x86_64-w64-mingw32-gcc -Wall -Wshadow -Wwrite-strings -Wundef -Wstrict-prototypes -Wunused -Wunused-parameter -Wunused-function -Wunused-value -Wmissing-prototypes -Wmissing-declarations -Wno-format-security -Wdeclaration-after-statement -Wold-style-definition -finline-limit=0 -fno-builtin-strlen -fomit-frame-pointer -ffunction-sections -fdata-sections -fno-guess-branch-probability -funsigned-char -static-libgcc -falign-functions=1 -falign-jumps=1 -falign-labels=1 -falign-loops=1 -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-builtin-printf -g -Os -funwind-tables -fasynchronous-unwind-tables -Iwin32 -DHAVE_STRING_H=1 -DHAVE_CONFIG_H=0 -fno-builtin-stpcpy -fno-ident -fno-builtin-strndup -fno-builtin-strcpy -o busybox_unstripped.exe -Wl,--sort-common -Wl,--sort-section,alignment -Wl,--gc-sections -Wl,--start-group applets/built-in.o win32/resources/built-in.o archival/lib.a archival/libarchive/lib.a console-tools/lib.a coreutils/lib.a coreutils/libcoreutils/lib.a debianutils/lib.a klibc-utils/lib.a e2fsprogs/lib.a editors/lib.a findutils/lib.a init/lib.a libbb/lib.a libpwdgrp/lib.a loginutils/lib.a mailutils/lib.a miscutils/lib.a modutils/lib.a networking/lib.a networking/libiproute/lib.a networking/udhcp/lib.a printutils/lib.a procps/lib.a runit/lib.a selinux/lib.a shell/lib.a sysklogd/lib.a util-linux/lib.a util-linux/volume_id/lib.a win32/lib.a archival/built-in.o archival/libarchive/built-in.o console-tools/built-in.o coreutils/built-in.o coreutils/libcoreutils/built-in.o debianutils/built-in.o klibc-utils/built-in.o e2fsprogs/built-in.o editors/built-in.o findutils/built-in.o init/built-in.o libbb/built-in.o libpwdgrp/built-in.o loginutils/built-in.o mailutils/built-in.o miscutils/built-in.o modutils/built-in.o networking/built-in.o networking/libiproute/built-in.o networking/udhcp/built-in.o printutils/built-in.o procps/built-in.o runit/built-in.o selinux/built-in.o shell/built-in.o sysklogd/built-in.o util-linux/built-in.o util-linux/volume_id/built-in.o win32/built-in.o -Wl,--end-group -Wl,--start-group -lws2_32 -Wl,--end-group
==========
/usr/lib/gcc/x86_64-w64-mingw32/10.2.1/../../../../x86_64-w64-mingw32/bin/ld: /usr/x86_64-w64-mingw32/sys-root/mingw/lib/../lib/libmingwex.a(lib64_libmingwex_a-dirent.o):(.text+0x2d6): undefined reference to `__strcpy_chk'
collect2: error: ld returned 1 exit status
```
Using a hint from this [bug report](https://sourceforge.net/p/mingw-w64/bugs/818/) I added ```ssp``` to ```LDLIBS``` in ```Makefile.flags``` and it worked.

**Comment by HuangShumin** [comment]
I tried appending `ssp` to `LDLIBS` after `ws2_32` in `Makefile.flags`, but failed again with no luck.
I didn't use Fedora 33 to build, I use MSYS2 instead. I confirmed this build failure is caused by new MinGW 10.2.0, because I can manage to build with MinGW 9.2

I'm still trying to find the solution.

**Comment by dscho** [comment]
I just experienced this, too (also using MSYS2 and mingw-w64-gcc v10.2.0). When I run `make V=1`, then copy-edit the link command _skipping_ `win32/resources/built-in.o`, the error goes away.

Side note: I had to set `WINDRES` because while I have `x86_64-w64-mingw32-gcc`, I don't have any `x86_64-w64-mingw32-windres` (and I do not know where such a thing might exist). But I do have `windres.exe`, therefore I simply used `make -j$(nproc) WINDRES=windres` to build BusyBox-w32.

And when I do that with `V=1`, I see that `windres` is called, and then `gcc`:

```
  windres -O coff -D"KBUILD_STR(s)=#s" -D"BB_VER=KBUILD_STR(1.34.0.git)" -D"BB_VERSION=1" -D"BB_PATCHLEVEL=34" -D"BB_SUBLEVEL=0" -D"BB_EXTRAVERSION=0" --include-dir=/usr/src/MINGW-packages/mingw-w64-busybox/src/busybox-w32/include --include-dir=/usr/src/MINGW-packages/mingw-w64-busybox/src/busybox-w32/win32/resources win32/resources/resources.rc win32/resources/resources.o
  x86_64-w64-mingw32-gcc -nostdlib -nostdlib  -r -o win32/resources/built-in.o win32/resources/resources.o
```

Now, the `-r` option [says](https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html#Link-Options) that it should be used to:

> Produce a relocatable object as output. This is also known as partial linking.

Essentially, this should only repackage the `resources.o` file as another `.o` file. On a hunch, I used the `resources.o` file instead of the `built-in.o` file for the link, and that worked. So it looks as if `gcc -r -o built-in.o resources.o` corrupts the contents and should be skipped. I only managed to find a hacky solution for that. Here is the diff of this hack:

```diff
diff --git a/Makefile b/Makefile
index a6609ca90..0f69533ce 100644
--- a/Makefile
+++ b/Makefile
@@ -613,7 +613,7 @@ quiet_cmd_busybox__ ?= LINK    $@
       "$(CC)" \
       "$(CFLAGS) $(CFLAGS_busybox)" \
       "$(LDFLAGS) $(EXTRA_LDFLAGS)" \
-      "$(core-y)" \
+      "$(filter-out win32/resources/built-in.o, $(core-y)) win32/resources/resources.o" \
       "$(libs-y)" \
       "$(LDLIBS)" \
       && $(srctree)/scripts/generate_BUFSIZ.sh --post include/common_bufsiz.h
```

I am too unfamiliar with Kbuild to know how to solve this better... @rmyorston do you have an idea?

**Comment by rmyorston** [comment]
The cardinal rule is that I don't do development work on Windows. This isn't really development, though, so I installed MSYS2 and gcc in a Windows 8.1 VM.

It took a while to get to the point of building busybox-w32:

- There was the thing about [no x86_64-w64-mingw32-windres.exe](https://github.com/msys2/MSYS2-packages/issues/937). The same applied to ```ar``` and ```strip```. I just made hardlinks.
- There were various issues with the build, which I'll put in a separate commit.
- For some reason the autogenerated include files ```NUM_APPLETS.h``` and ```applet_tables.h``` came out as ```NUM_APPLETS.h.1234.new``` and ```applet_tables.h.1234.new```. I just renamed them and carried on.

Eventually the build failed with the '0-bit reloc' error.

I compared the files generated under MSYS2 with those from my Fedora 33 cross-compilation build environment (which has mingw64-gcc-10.2.1-2). The ```resources.o``` files were identical; the ```built-in.o``` files were the same size but had different content. Running ```objdump -r``` gave this for the cross-compiled version:
```
built-in.o:     file format pe-x86-64

RELOCATION RECORDS FOR [.rsrc]:
OFFSET           TYPE              VALUE 
0000000000000178 rva32             .rsrc
0000000000000188 rva32             .rsrc
0000000000000198 rva32             .rsrc
00000000000001a8 rva32             .rsrc
00000000000001b8 rva32             .rsrc
00000000000001c8 rva32             .rsrc
00000000000001d8 rva32             .rsrc
00000000000001e8 rva32             .rsrc
00000000000001f8 rva32             .rsrc
```
and this for MSYS2:
```
built-in.o:     file format pe-x86-64

RELOCATION RECORDS FOR [.rsrc]:
OFFSET           TYPE              VALUE 
0000000000000000 0                 .rsrc
0000000000000000 0                 .rsrc
0000000000000000 0                 .rsrc
0000000000000000 0                 .rsrc
0000000000000000 0                 .rsrc
0000000000000000 0                 .rsrc
0000000000000000 0                 .rsrc
0000000000000000 0                 .rsrc
0000000000000000 0                 .rsrc
```
The linker spoke the truth: 0-bit relocations. Looks like a bug to me.

Now, the ```win32/resources``` directory contains a ```dummy.c``` file to persuade the build system there's something worth looking at. On a whim I put some code in it to see if it would make any difference:
```diff
diff --git a/win32/resources/Kbuild.src b/win32/resources/Kbuild.src
index 1900d1872..550eddaa0 100644
--- a/win32/resources/Kbuild.src
+++ b/win32/resources/Kbuild.src
@@ -7,6 +7,7 @@
 obj-y :=
 
 obj-$(CONFIG_FEATURE_RESOURCES) += resources.o
+obj-$(CONFIG_FEATURE_RESOURCES) += dummy.o
 
 # return commit level if available or 0
 bb_level = $(or $(word 2,$(subst -, ,$1)),0)
diff --git a/win32/resources/dummy.c b/win32/resources/dummy.c
index e69de29bb..3589517ea 100644
--- a/win32/resources/dummy.c
+++ b/win32/resources/dummy.c
@@ -0,0 +1,2 @@
+extern void wibble(void);
+void wibble(void) {}
```
It worked. The build succeeded and ```objdump -r built-in.o``` showed:
```
built-in.o:     file format pe-x86-64

RELOCATION RECORDS FOR [.pdata$wibble]:
OFFSET           TYPE              VALUE
0000000000000000 IMAGE_REL_AMD64_ADDR32NB  .text$wibble
0000000000000004 IMAGE_REL_AMD64_ADDR32NB  .text$wibble
0000000000000008 IMAGE_REL_AMD64_ADDR32NB  .xdata$wibble

RELOCATION RECORDS FOR [.rsrc]:
OFFSET           TYPE              VALUE
0000000000000178 IMAGE_REL_AMD64_ADDR32NB  .rsrc
0000000000000188 IMAGE_REL_AMD64_ADDR32NB  .rsrc
0000000000000198 IMAGE_REL_AMD64_ADDR32NB  .rsrc
00000000000001a8 IMAGE_REL_AMD64_ADDR32NB  .rsrc
00000000000001b8 IMAGE_REL_AMD64_ADDR32NB  .rsrc
00000000000001c8 IMAGE_REL_AMD64_ADDR32NB  .rsrc
00000000000001d8 IMAGE_REL_AMD64_ADDR32NB  .rsrc
00000000000001e8 IMAGE_REL_AMD64_ADDR32NB  .rsrc
00000000000001f8 IMAGE_REL_AMD64_ADDR32NB  .rsrc
...
```
Non-zero relocations as far as the eye can see!

**Comment by rmyorston** [comment]
The problem also affects 32-bit builds. The same mitigation is effective there too.

With the latest code in git busybox-w32 builds on MSYS2/mingw-w64. I've added some information to the README.

**Comment by dscho** [comment]
> With the latest code in git busybox-w32 builds on MSYS2/mingw-w64. I've added some information to the README.

That works for me. With that change, I am in favor of closing this ticket as resolved.

**Comment by HuangShumin** [comment]
Great works! Awesome all of you.
